// =====================================================
// AUTO-GENERATED BY train_model.py — DO NOT EDIT
// Model: Random Forest (30 trees, max_depth=8)
// Input:  float features[61]
//   [0..19]  fark_t0..19       (raw delta values)
//   [20..39] norm_t0..19       (normalized shape, distance-independent)
//   [40..58] slope_i_(i+1)     (consecutive decay slopes)
//   [59]     energy             (sum of all fark values)
//   [60]     decay_rate         (early avg - late avg, ferrous indicator)
// Output: int classIndex
//   0=NoMetal, 1=Aluminium, 4=Steel
// Training accuracy: 88.1%
// CV accuracy:       92.8%
// =====================================================

#ifndef METAL_MODEL_H
#define METAL_MODEL_H

#define NUM_CLASSES  3
#define NUM_FEATURES 61

// Class label strings — index matches model output
const char* CLASS_LABELS[NUM_CLASSES] = {
  "NoMetal", "Aluminium", "Steel"
};

// Minimum vote fraction to accept a prediction
// Below this → display "Unknown"
#define CONFIDENCE_THRESHOLD 0.70f

// ── m2cgen generated model (pure C, no libraries) ──
#include <string.h>
void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
void score(double * input, double * output) {
    double var0[3];
    double var1[3];
    double var2[3];
    double var3[3];
    double var4[3];
    double var5[3];
    double var6[3];
    double var7[3];
    double var8[3];
    double var9[3];
    double var10[3];
    double var11[3];
    double var12[3];
    double var13[3];
    double var14[3];
    double var15[3];
    double var16[3];
    double var17[3];
    double var18[3];
    double var19[3];
    double var20[3];
    double var21[3];
    double var22[3];
    double var23[3];
    double var24[3];
    double var25[3];
    double var26[3];
    double var27[3];
    double var28[3];
    double var29[3];
    double var30[3];
    if (input[10] <= 80.45000076293945) {
        if (input[9] <= 5.299999952316284) {
            if (input[2] <= 0.15000000596046448) {
                memcpy(var30, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[22] <= 1.1083326935768127) {
                    if (input[59] <= 61.44999694824219) {
                        if (input[2] <= 2.850000023841858) {
                            if (input[58] <= 1.350000023841858) {
                                if (input[42] <= 1.2000000476837158) {
                                    memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[9] <= 1.5999999642372131) {
                                    memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var30, (double[]){0.0, 0.9166666666666666, 0.08333333333333333}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                } else {
                    if (input[3] <= 3.0500000715255737) {
                        if (input[50] <= -1.4500000476837158) {
                            memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[13] <= 1.2000000178813934) {
                                if (input[27] <= 2.7499948143959045) {
                                    memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            if (input[8] <= 14.400000095367432) {
                memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                if (input[1] <= 38.04999923706055) {
                    memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    memcpy(var30, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            }
        }
    } else {
        memcpy(var30, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    double var31[3];
    if (input[13] <= 14.25) {
        if (input[18] <= 7.1499998569488525) {
            if (input[2] <= 0.15000000596046448) {
                memcpy(var31, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[7] <= 2.350000023841858) {
                    if (input[2] <= 2.25) {
                        if (input[44] <= 1.449999988079071) {
                            if (input[47] <= 1.9499999284744263) {
                                memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[31] <= 1.2574365139007568) {
                                    memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[56] <= 0.04999995231628418) {
                            memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        } else {
                            if (input[27] <= 0.568499356508255) {
                                memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    }
                } else {
                    if (input[16] <= 3.100000023841858) {
                        if (input[2] <= 3.4499999284744263) {
                            if (input[23] <= 0.9519228041172028) {
                                memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[29] <= 700000.4999996722) {
                                    memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[3] <= 38.5) {
            memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            if (input[5] <= 80.25) {
                memcpy(var31, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                memcpy(var31, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    add_vectors(var30, var31, 3, var29);
    double var32[3];
    if (input[59] <= 259.25) {
        if (input[1] <= 5.6499998569488525) {
            if (input[9] <= 0.20000000298023224) {
                if (input[59] <= 14.699999809265137) {
                    memcpy(var32, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                } else {
                    if (input[59] <= 34.39999771118164) {
                        memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            } else {
                if (input[12] <= 3.600000023841858) {
                    if (input[45] <= 0.3500000238418579) {
                        if (input[7] <= 2.6999999284744263) {
                            if (input[11] <= 0.6000000238418579) {
                                if (input[59] <= 11.900000095367432) {
                                    memcpy(var32, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[8] <= 1.300000011920929) {
                                    memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[21] <= 0.9028209447860718) {
                                memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[19] <= 2.350000023841858) {
                            memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[48] <= -0.15000009536743164) {
                                if (input[45] <= 2.600000023841858) {
                                    memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[46] <= 0.25) {
                                    memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[41] <= 0.8000001907348633) {
                        if (input[37] <= 0.44418229162693024) {
                            if (input[23] <= 0.5456348210573196) {
                                memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[13] <= 38.29999923706055) {
            memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            if (input[6] <= 80.3499984741211) {
                memcpy(var32, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                memcpy(var32, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    add_vectors(var29, var32, 3, var28);
    double var33[3];
    if (input[18] <= 12.699999809265137) {
        if (input[15] <= 6.400000095367432) {
            if (input[22] <= 0.049999985843896866) {
                memcpy(var33, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[52] <= -1.5499999523162842) {
                    if (input[28] <= 0.42994324862957) {
                        memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                } else {
                    if (input[5] <= 2.149999976158142) {
                        if (input[22] <= 0.5539214313030243) {
                            if (input[31] <= 1.26328444480896) {
                                if (input[4] <= 2.199999988079071) {
                                    memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var33, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[59] <= 34.44999885559082) {
                                memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[17] <= 3.1999999284744263) {
                                    memcpy(var33, (double[]){0.0, 0.03333333333333333, 0.9666666666666667}, 3 * sizeof(double));
                                } else {
                                    memcpy(var33, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        if (input[22] <= 1.1081078052520752) {
                            memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[11] <= 4.049999952316284) {
                                memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    }
                }
            }
        } else {
            if (input[11] <= 15.449999809265137) {
                memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    } else {
        if (input[11] <= 78.79999923706055) {
            if (input[8] <= 37.75) {
                if (input[4] <= 12.25) {
                    memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                } else {
                    memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var33, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var33, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var28, var33, 3, var27);
    double var34[3];
    if (input[17] <= 78.5) {
        if (input[17] <= 37.89999961853027) {
            if (input[19] <= 13.849999904632568) {
                if (input[15] <= 5.700000047683716) {
                    if (input[10] <= 0.44999999552965164) {
                        memcpy(var34, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[59] <= 60.85000038146973) {
                            if (input[5] <= 0.7999999821186066) {
                                memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[1] <= 5.1499998569488525) {
                                    memcpy(var34, (double[]){0.0, 0.1896551724137931, 0.8103448275862069}, 3 * sizeof(double));
                                } else {
                                    memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var34, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var34, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var34, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var27, var34, 3, var26);
    double var35[3];
    if (input[16] <= 14.150000095367432) {
        if (input[17] <= 6.950000047683716) {
            if (input[1] <= 3.75) {
                if (input[48] <= -0.949999988079071) {
                    if (input[13] <= 0.20000000298023224) {
                        memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    if (input[52] <= -0.30000007152557373) {
                        if (input[60] <= 0.20000016689300537) {
                            if (input[43] <= 2.2500001192092896) {
                                if (input[36] <= 0.06338027119636536) {
                                    memcpy(var35, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var35, (double[]){0.0, 0.972972972972973, 0.02702702702702703}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[49] <= -1.4499998092651367) {
                                memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[31] <= 0.13636352121829987) {
                            memcpy(var35, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[11] <= 2.3000000715255737) {
                                if (input[3] <= 1.8499999642372131) {
                                    memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var35, (double[]){0.0, 0.16666666666666666, 0.8333333333333334}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[55] <= -2.0499998331069946) {
                                    memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                }
            } else {
                if (input[40] <= -2.5) {
                    memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                } else {
                    if (input[53] <= 1.5500001907348633) {
                        memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[59] <= 745.6499633789062) {
            memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            if (input[12] <= 79.14999771118164) {
                memcpy(var35, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                memcpy(var35, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    add_vectors(var26, var35, 3, var25);
    double var36[3];
    if (input[10] <= 79.29999923706055) {
        if (input[17] <= 37.89999961853027) {
            if (input[3] <= 12.849999904632568) {
                if (input[17] <= 6.950000047683716) {
                    if (input[10] <= 0.05000000074505806) {
                        memcpy(var36, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[27] <= 0.5305554270744324) {
                            if (input[48] <= -0.1499999761581421) {
                                if (input[7] <= 2.100000023841858) {
                                    memcpy(var36, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[26] <= 0.5310455858707428) {
                                    memcpy(var36, (double[]){0.0, 0.25, 0.75}, 3 * sizeof(double));
                                } else {
                                    memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[5] <= 4.400000095367432) {
                                if (input[16] <= 3.100000023841858) {
                                    memcpy(var36, (double[]){0.0, 0.75, 0.25}, 3 * sizeof(double));
                                } else {
                                    memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var36, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    }
                } else {
                    memcpy(var36, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var36, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var36, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var25, var36, 3, var24);
    double var37[3];
    if (input[8] <= 80.25) {
        if (input[8] <= 37.75) {
            if (input[3] <= 11.799999713897705) {
                if (input[14] <= 4.400000095367432) {
                    if (input[8] <= 0.3500000089406967) {
                        if (input[51] <= -0.25) {
                            memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var37, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[22] <= 0.98148113489151) {
                            if (input[59] <= 61.44999694824219) {
                                if (input[2] <= 2.25) {
                                    memcpy(var37, (double[]){0.0, 0.875, 0.125}, 3 * sizeof(double));
                                } else {
                                    memcpy(var37, (double[]){0.0, 0.13333333333333333, 0.8666666666666667}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[42] <= -1.7999999523162842) {
                                memcpy(var37, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[32] <= 1.0572576522827148) {
                                    memcpy(var37, (double[]){0.0, 0.16666666666666666, 0.8333333333333334}, 3 * sizeof(double));
                                } else {
                                    memcpy(var37, (double[]){0.0, 0.8, 0.2}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[27] <= 0.4581223130226135) {
                        memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var37, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var37, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var37, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var24, var37, 3, var23);
    double var38[3];
    if (input[19] <= 77.5999984741211) {
        if (input[2] <= 36.5) {
            if (input[0] <= 12.849999904632568) {
                if (input[21] <= 0.09615381807088852) {
                    memcpy(var38, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                } else {
                    if (input[16] <= 4.949999809265137) {
                        if (input[1] <= 0.4000000059604645) {
                            if (input[18] <= 2.350000023841858) {
                                memcpy(var38, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var38, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[4] <= 3.149999976158142) {
                                if (input[57] <= 0.0) {
                                    memcpy(var38, (double[]){0.0, 0.7727272727272727, 0.22727272727272727}, 3 * sizeof(double));
                                } else {
                                    memcpy(var38, (double[]){0.0, 0.42592592592592593, 0.5740740740740741}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var38, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        memcpy(var38, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var38, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var38, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var38, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var23, var38, 3, var22);
    double var39[3];
    if (input[4] <= 79.0999984741211) {
        if (input[4] <= 39.20000076293945) {
            if (input[3] <= 12.549999713897705) {
                if (input[9] <= 5.3500001430511475) {
                    if (input[22] <= 0.049999985843896866) {
                        memcpy(var39, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[50] <= 1.0) {
                            if (input[22] <= 1.1661437153816223) {
                                if (input[43] <= -0.6500000953674316) {
                                    memcpy(var39, (double[]){0.0, 0.5714285714285714, 0.42857142857142855}, 3 * sizeof(double));
                                } else {
                                    memcpy(var39, (double[]){0.0, 0.8928571428571429, 0.10714285714285714}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[0] <= 0.8999999910593033) {
                                    memcpy(var39, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var39, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[28] <= 1.0283015668392181) {
                                if (input[59] <= 61.79999923706055) {
                                    memcpy(var39, (double[]){0.0, 0.1111111111111111, 0.8888888888888888}, 3 * sizeof(double));
                                } else {
                                    memcpy(var39, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[17] <= 1.75) {
                                    memcpy(var39, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var39, (double[]){0.0, 0.9230769230769231, 0.07692307692307693}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    memcpy(var39, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var39, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var39, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var39, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var22, var39, 3, var21);
    double var40[3];
    if (input[3] <= 79.3499984741211) {
        if (input[2] <= 36.5) {
            if (input[4] <= 13.449999809265137) {
                if (input[8] <= 6.200000047683716) {
                    if (input[42] <= -1.850000023841858) {
                        memcpy(var40, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        if (input[4] <= 0.5499999970197678) {
                            if (input[40] <= 0.3999999910593033) {
                                memcpy(var40, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var40, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[56] <= -0.44999992847442627) {
                                if (input[27] <= 0.6074559986591339) {
                                    memcpy(var40, (double[]){0.0, 0.14285714285714285, 0.8571428571428571}, 3 * sizeof(double));
                                } else {
                                    memcpy(var40, (double[]){0.0, 0.7222222222222222, 0.2777777777777778}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[37] <= 1.443749189376831) {
                                    memcpy(var40, (double[]){0.0, 0.9038461538461539, 0.09615384615384616}, 3 * sizeof(double));
                                } else {
                                    memcpy(var40, (double[]){0.0, 0.25, 0.75}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    memcpy(var40, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var40, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var40, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var40, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var21, var40, 3, var20);
    double var41[3];
    if (input[59] <= 1591.0499877929688) {
        if (input[16] <= 37.60000038146973) {
            if (input[14] <= 13.950000286102295) {
                if (input[3] <= 4.150000095367432) {
                    if (input[10] <= 0.25) {
                        memcpy(var41, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[42] <= -1.899999976158142) {
                            memcpy(var41, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        } else {
                            if (input[7] <= 2.649999976158142) {
                                if (input[17] <= 3.9499999284744263) {
                                    memcpy(var41, (double[]){0.0, 0.24242424242424243, 0.7575757575757576}, 3 * sizeof(double));
                                } else {
                                    memcpy(var41, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[27] <= 1.8181807398796082) {
                                    memcpy(var41, (double[]){0.0, 0.9166666666666666, 0.08333333333333333}, 3 * sizeof(double));
                                } else {
                                    memcpy(var41, (double[]){0.0, 0.3333333333333333, 0.6666666666666666}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[37] <= 0.6138908565044403) {
                        memcpy(var41, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var41, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var41, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var41, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var41, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var20, var41, 3, var19);
    double var42[3];
    if (input[17] <= 77.1500015258789) {
        if (input[13] <= 37.75) {
            if (input[12] <= 14.400000095367432) {
                if (input[19] <= 6.3999998569488525) {
                    if (input[21] <= 0.12499990314245224) {
                        if (input[46] <= -1.2000000476837158) {
                            memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var42, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[45] <= 0.40000003576278687) {
                            if (input[7] <= 2.649999976158142) {
                                if (input[28] <= 0.2073170393705368) {
                                    memcpy(var42, (double[]){0.3333333333333333, 0.6666666666666666, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var42, (double[]){0.043478260869565216, 0.043478260869565216, 0.9130434782608695}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[42] <= -1.6000001430511475) {
                                    memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var42, (double[]){0.0, 0.9090909090909091, 0.09090909090909091}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[55] <= -3.1499998569488525) {
                                memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[40] <= -0.10000002384185791) {
                                    memcpy(var42, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var42, (double[]){0.0, 0.88, 0.12}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var42, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var42, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var42, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var19, var42, 3, var18);
    double var43[3];
    if (input[4] <= 79.29999923706055) {
        if (input[8] <= 38.54999923706055) {
            if (input[33] <= 1.0416663885116577) {
                if (input[4] <= 12.049999713897705) {
                    if (input[16] <= 4.849999904632568) {
                        if (input[10] <= 0.05000000074505806) {
                            memcpy(var43, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[26] <= 0.5340907871723175) {
                                if (input[1] <= 3.0) {
                                    memcpy(var43, (double[]){0.0, 0.8666666666666667, 0.13333333333333333}, 3 * sizeof(double));
                                } else {
                                    memcpy(var43, (double[]){0.0, 0.2777777777777778, 0.7222222222222222}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[54] <= 2.2500001192092896) {
                                    memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var43, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var43, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            } else {
                if (input[6] <= 13.400000095367432) {
                    if (input[3] <= 4.5) {
                        if (input[22] <= 0.08974356204271317) {
                            memcpy(var43, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[7] <= 2.950000047683716) {
                                if (input[12] <= 0.5) {
                                    memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var43, (double[]){0.0, 0.1, 0.9}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[0] <= 2.75) {
                                    memcpy(var43, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                } else {
                                    memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var43, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            memcpy(var43, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var43, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var18, var43, 3, var17);
    double var44[3];
    if (input[59] <= 259.25) {
        if (input[5] <= 4.100000023841858) {
            if (input[34] <= 0.0161290280520916) {
                if (input[53] <= -1.199999988079071) {
                    if (input[39] <= 0.652173638343811) {
                        memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var44, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                }
            } else {
                if (input[7] <= 2.649999976158142) {
                    if (input[9] <= 1.600000023841858) {
                        if (input[21] <= 1.7330819368362427) {
                            if (input[53] <= -1.0999999642372131) {
                                memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[45] <= 0.40000003576278687) {
                            if (input[57] <= -1.5499999523162842) {
                                memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[28] <= 1.1639780402183533) {
                                    memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    if (input[53] <= 2.150000214576721) {
                        if (input[60] <= 1.0499999523162842) {
                            if (input[52] <= 2.450000047683716) {
                                if (input[33] <= 2.6515133380889893) {
                                    memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var44, (double[]){0.0, 0.75, 0.25}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[1] <= 1.2999999821186066) {
                                    memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[35] <= 0.5619044303894043) {
                            memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    }
                }
            }
        } else {
            memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[13] <= 37.80000019073486) {
            memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        } else {
            if (input[4] <= 79.0999984741211) {
                memcpy(var44, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            } else {
                memcpy(var44, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    add_vectors(var17, var44, 3, var16);
    double var45[3];
    if (input[12] <= 79.14999771118164) {
        if (input[10] <= 38.35000038146973) {
            if (input[5] <= 14.5) {
                if (input[8] <= 6.099999904632568) {
                    if (input[10] <= 0.3500000014901161) {
                        if (input[2] <= 0.25) {
                            memcpy(var45, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[59] <= 61.44999694824219) {
                            if (input[45] <= 0.40000003576278687) {
                                if (input[56] <= 2.1999999284744263) {
                                    memcpy(var45, (double[]){0.0, 0.2727272727272727, 0.7272727272727273}, 3 * sizeof(double));
                                } else {
                                    memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[46] <= 1.2500000596046448) {
                                    memcpy(var45, (double[]){0.0, 0.9285714285714286, 0.07142857142857142}, 3 * sizeof(double));
                                } else {
                                    memcpy(var45, (double[]){0.0, 0.3333333333333333, 0.6666666666666666}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var45, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var45, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var45, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var16, var45, 3, var15);
    double var46[3];
    if (input[18] <= 77.39999771118164) {
        if (input[19] <= 37.45000076293945) {
            if (input[7] <= 13.950000286102295) {
                if (input[2] <= 3.6999999284744263) {
                    if (input[59] <= 11.099999904632568) {
                        memcpy(var46, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[6] <= 1.8499999642372131) {
                            if (input[22] <= 0.7403843998908997) {
                                if (input[55] <= -0.5000001192092896) {
                                    memcpy(var46, (double[]){0.0, 0.2727272727272727, 0.7272727272727273}, 3 * sizeof(double));
                                } else {
                                    memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[26] <= 0.0645161122083664) {
                                    memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var46, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[22] <= 0.7547845244407654) {
                                memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[32] <= 0.9240382015705109) {
                                    memcpy(var46, (double[]){0.0, 0.25, 0.75}, 3 * sizeof(double));
                                } else {
                                    memcpy(var46, (double[]){0.0, 0.9411764705882353, 0.058823529411764705}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[40] <= 0.7500002384185791) {
                        memcpy(var46, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        if (input[55] <= -0.39999985694885254) {
                            memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var46, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    }
                }
            } else {
                memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var46, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var46, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var15, var46, 3, var14);
    double var47[3];
    if (input[3] <= 79.3499984741211) {
        if (input[16] <= 37.60000038146973) {
            if (input[5] <= 14.699999809265137) {
                if (input[9] <= 6.800000190734863) {
                    if (input[28] <= 0.1612902730703354) {
                        if (input[29] <= 0.2115383893251419) {
                            memcpy(var47, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[9] <= 2.649999976158142) {
                            if (input[59] <= 32.14999866485596) {
                                if (input[7] <= 0.5500000007450581) {
                                    memcpy(var47, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[22] <= 0.45437775552272797) {
                                    memcpy(var47, (double[]){0.0, 0.8333333333333334, 0.16666666666666666}, 3 * sizeof(double));
                                } else {
                                    memcpy(var47, (double[]){0.0, 0.13793103448275862, 0.8620689655172413}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[27] <= 1.4728347659111023) {
                                if (input[22] <= 1.693547546863556) {
                                    memcpy(var47, (double[]){0.0, 0.9166666666666666, 0.08333333333333333}, 3 * sizeof(double));
                                } else {
                                    memcpy(var47, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[29] <= 4.199993252754211) {
                                    memcpy(var47, (double[]){0.0, 0.1111111111111111, 0.8888888888888888}, 3 * sizeof(double));
                                } else {
                                    memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[4] <= 13.300000190734863) {
                        memcpy(var47, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var47, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var47, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var14, var47, 3, var13);
    double var48[3];
    if (input[0] <= 12.849999904632568) {
        if (input[28] <= 0.07777775824069977) {
            if (input[53] <= 0.19999998807907104) {
                memcpy(var48, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[46] <= -0.34999996423721313) {
                    memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    memcpy(var48, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            if (input[18] <= 6.849999904632568) {
                if (input[7] <= 2.25) {
                    if (input[60] <= 0.43333321809768677) {
                        if (input[46] <= -0.15000003576278687) {
                            memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[23] <= 0.16596630215644836) {
                                if (input[41] <= 0.44999995827674866) {
                                    memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var48, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    if (input[24] <= 0.9115381836891174) {
                        if (input[34] <= 0.04545452445745468) {
                            if (input[5] <= 2.049999952316284) {
                                memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[44] <= 3.549999952316284) {
                                memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[41] <= -0.3500000238418579) {
                            if (input[48] <= -0.75) {
                                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    }
                }
            } else {
                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        }
    } else {
        if (input[16] <= 79.04999923706055) {
            if (input[5] <= 37.749999046325684) {
                memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            } else {
                memcpy(var48, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var48, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var13, var48, 3, var12);
    double var49[3];
    if (input[18] <= 77.89999771118164) {
        if (input[17] <= 37.89999961853027) {
            if (input[11] <= 14.150000095367432) {
                if (input[2] <= 4.099999904632568) {
                    if (input[9] <= 0.30000000447034836) {
                        if (input[5] <= 0.2500000037252903) {
                            memcpy(var49, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[31] <= 0.8611106872558594) {
                                memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[43] <= -0.8500000238418579) {
                            if (input[2] <= 1.449999988079071) {
                                memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            } else {
                                if (input[10] <= 4.350000023841858) {
                                    memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[37] <= 0.28914135694503784) {
                                if (input[50] <= 0.7999999523162842) {
                                    memcpy(var49, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[7] <= 2.3000000715255737) {
                                    memcpy(var49, (double[]){0.0, 0.5714285714285714, 0.42857142857142855}, 3 * sizeof(double));
                                } else {
                                    memcpy(var49, (double[]){0.0, 0.9310344827586207, 0.06896551724137931}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var49, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var49, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var12, var49, 3, var11);
    double var50[3];
    if (input[14] <= 14.150000095367432) {
        if (input[18] <= 5.3999998569488525) {
            if (input[30] <= 0.09090907126665115) {
                memcpy(var50, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[6] <= 2.950000047683716) {
                    if (input[22] <= 0.9119921028614044) {
                        if (input[27] <= 0.5857840776443481) {
                            if (input[49] <= 1.25) {
                                if (input[22] <= 0.3999999314546585) {
                                    memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var50, (double[]){0.0, 0.1, 0.9}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[41] <= 1.000000149011612) {
                            if (input[43] <= -0.4500000476837158) {
                                memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[42] <= -2.399999976158142) {
                                    memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    if (input[9] <= 0.25) {
                        memcpy(var50, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            if (input[10] <= 2.799999952316284) {
                if (input[44] <= -1.25) {
                    memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        }
    } else {
        if (input[38] <= 0.957381933927536) {
            if (input[18] <= 38.40000057220459) {
                memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[14] <= 79.5) {
                    memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                } else {
                    memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            if (input[0] <= 79.39999771118164) {
                if (input[3] <= 36.35000038146973) {
                    memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    memcpy(var50, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var50, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        }
    }
    add_vectors(var11, var50, 3, var10);
    double var51[3];
    if (input[8] <= 80.20000076293945) {
        if (input[17] <= 38.10000038146973) {
            if (input[2] <= 12.300000190734863) {
                if (input[6] <= 6.1000001430511475) {
                    if (input[8] <= 0.3500000089406967) {
                        if (input[31] <= 0.19230763614177704) {
                            memcpy(var51, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        } else {
                            if (input[49] <= 0.04999998211860657) {
                                memcpy(var51, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var51, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[41] <= 1.2000001668930054) {
                            if (input[57] <= 0.25) {
                                if (input[24] <= 0.2740640267729759) {
                                    memcpy(var51, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var51, (double[]){0.0, 0.9354838709677419, 0.06451612903225806}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[59] <= 60.60000038146973) {
                                    memcpy(var51, (double[]){0.0, 0.4090909090909091, 0.5909090909090909}, 3 * sizeof(double));
                                } else {
                                    memcpy(var51, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var51, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var51, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var51, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var51, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var51, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var10, var51, 3, var9);
    double var52[3];
    if (input[12] <= 79.14999771118164) {
        if (input[18] <= 37.75) {
            if (input[23] <= 0.8692104518413544) {
                if (input[2] <= 4.099999904632568) {
                    if (input[10] <= 0.4000000134110451) {
                        memcpy(var52, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[58] <= 1.0499999523162842) {
                            if (input[41] <= 1.4999999403953552) {
                                if (input[42] <= -2.149999976158142) {
                                    memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var52, (double[]){0.0, 0.8958333333333334, 0.10416666666666667}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[7] <= 2.4499999284744263) {
                                memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[40] <= -0.25) {
                                    memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    if (input[9] <= 16.59999990463257) {
                        memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            } else {
                if (input[0] <= 12.400000095367432) {
                    if (input[18] <= 7.799999713897705) {
                        if (input[35] <= 1.2111105918884277) {
                            if (input[42] <= 1.8500001430511475) {
                                if (input[26] <= 1.1880338788032532) {
                                    memcpy(var52, (double[]){0.0, 0.07142857142857142, 0.9285714285714286}, 3 * sizeof(double));
                                } else {
                                    memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[54] <= -0.30000004172325134) {
                                memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[12] <= 0.350000012665987) {
                                    memcpy(var52, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            memcpy(var52, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var52, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var9, var52, 3, var8);
    double var53[3];
    if (input[8] <= 14.400000095367432) {
        if (input[1] <= 6.049999952316284) {
            if (input[2] <= 0.15000000596046448) {
                memcpy(var53, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[17] <= 3.549999952316284) {
                    if (input[59] <= 61.099998474121094) {
                        if (input[9] <= 1.1500000357627869) {
                            if (input[24] <= 250000.0) {
                                if (input[29] <= 0.09210523962974548) {
                                    memcpy(var53, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                } else {
                                    memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var53, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[31] <= 0.7698409557342529) {
                                if (input[3] <= 1.600000023841858) {
                                    memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var53, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[6] <= 3.049999952316284) {
                                    memcpy(var53, (double[]){0.0, 0.0625, 0.9375}, 3 * sizeof(double));
                                } else {
                                    memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                } else {
                    if (input[50] <= 1.7500001192092896) {
                        memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var53, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            }
        } else {
            memcpy(var53, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[14] <= 76.94999694824219) {
            if (input[15] <= 37.84999942779541) {
                memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            } else {
                memcpy(var53, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var53, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var8, var53, 3, var7);
    double var54[3];
    if (input[19] <= 76.29999923706055) {
        if (input[1] <= 37.89999961853027) {
            if (input[3] <= 12.849999904632568) {
                if (input[18] <= 7.049999952316284) {
                    if (input[42] <= -2.149999976158142) {
                        memcpy(var54, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        if (input[38] <= 0.03846152499318123) {
                            if (input[7] <= 2.300000011920929) {
                                memcpy(var54, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var54, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        } else {
                            if (input[43] <= -0.34999993443489075) {
                                if (input[56] <= -0.20000004768371582) {
                                    memcpy(var54, (double[]){0.0, 0.2857142857142857, 0.7142857142857143}, 3 * sizeof(double));
                                } else {
                                    memcpy(var54, (double[]){0.045454545454545456, 0.7272727272727273, 0.22727272727272727}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[37] <= 1.9833323955535889) {
                                    memcpy(var54, (double[]){0.0, 0.98, 0.02}, 3 * sizeof(double));
                                } else {
                                    memcpy(var54, (double[]){0.3333333333333333, 0.16666666666666666, 0.5}, 3 * sizeof(double));
                                }
                            }
                        }
                    }
                } else {
                    memcpy(var54, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var54, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var54, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var54, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var7, var54, 3, var6);
    double var55[3];
    if (input[7] <= 14.550000190734863) {
        if (input[14] <= 4.1499998569488525) {
            if (input[13] <= 4.1499998569488525) {
                if (input[6] <= 2.950000047683716) {
                    if (input[51] <= 0.5999999940395355) {
                        if (input[46] <= 2.450000047683716) {
                            if (input[15] <= 1.449999988079071) {
                                if (input[27] <= 300000.3684209585) {
                                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var55, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[17] <= 4.1499998569488525) {
                                    memcpy(var55, (double[]){0.0, 0.08333333333333333, 0.9166666666666666}, 3 * sizeof(double));
                                } else {
                                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[19] <= 2.449999988079071) {
                                if (input[58] <= -1.3999999985098839) {
                                    memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[30] <= 0.6846151351928711) {
                            if (input[19] <= 3.299999952316284) {
                                memcpy(var55, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                            } else {
                                memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            }
                        } else {
                            memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            } else {
                if (input[37] <= 0.5935142040252686) {
                    memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                } else {
                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            if (input[16] <= 0.949999988079071) {
                memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            } else {
                memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        }
    } else {
        if (input[33] <= 0.9640632271766663) {
            if (input[39] <= 0.9677468836307526) {
                if (input[1] <= 38.0) {
                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    if (input[19] <= 81.95000076293945) {
                        memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            if (input[38] <= 0.9722055792808533) {
                if (input[13] <= 39.20000076293945) {
                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                } else {
                    if (input[17] <= 77.25) {
                        memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    } else {
                        memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                    }
                }
            } else {
                if (input[56] <= -1.5500011444091797) {
                    if (input[28] <= 1.0555436611175537) {
                        if (input[42] <= 2.1499996185302734) {
                            memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                        }
                    } else {
                        memcpy(var55, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var55, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        }
    }
    add_vectors(var6, var55, 3, var5);
    double var56[3];
    if (input[7] <= 78.29999923706055) {
        if (input[59] <= 747.8999328613281) {
            if (input[17] <= 14.25) {
                if (input[17] <= 6.349999904632568) {
                    if (input[10] <= 0.05000000074505806) {
                        memcpy(var56, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                    } else {
                        if (input[59] <= 62.64999580383301) {
                            if (input[3] <= 1.6500000357627869) {
                                if (input[11] <= 3.100000023841858) {
                                    memcpy(var56, (double[]){0.047619047619047616, 0.9523809523809523, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var56, (double[]){0.0, 0.4, 0.6}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[60] <= -1.0833333134651184) {
                                    memcpy(var56, (double[]){0.0, 0.5, 0.5}, 3 * sizeof(double));
                                } else {
                                    memcpy(var56, (double[]){0.0, 0.13333333333333333, 0.8666666666666667}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var56, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var56, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var56, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var56, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var56, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var5, var56, 3, var4);
    double var57[3];
    if (input[11] <= 79.19999694824219) {
        if (input[20] <= 0.9999989867210388) {
            if (input[39] <= 1.4999961853027344) {
                memcpy(var57, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
            } else {
                if (input[13] <= 0.44999999552965164) {
                    memcpy(var57, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                } else {
                    memcpy(var57, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            }
        } else {
            if (input[11] <= 39.54999923706055) {
                if (input[13] <= 14.099999904632568) {
                    if (input[5] <= 4.400000095367432) {
                        if (input[52] <= 0.14999991655349731) {
                            if (input[1] <= 0.25) {
                                memcpy(var57, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[0] <= 1.5) {
                                    memcpy(var57, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var57, (double[]){0.0, 0.9259259259259259, 0.07407407407407407}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[0] <= 3.75) {
                                if (input[25] <= 0.24972183257341385) {
                                    memcpy(var57, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var57, (double[]){0.0, 0.09090909090909091, 0.9090909090909091}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[12] <= 1.100000023841858) {
                                    memcpy(var57, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var57, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var57, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                } else {
                    memcpy(var57, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var57, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        }
    } else {
        memcpy(var57, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var4, var57, 3, var3);
    double var58[3];
    if (input[0] <= 80.29999923706055) {
        if (input[0] <= 40.04999923706055) {
            if (input[59] <= 259.25) {
                if (input[6] <= 5.5) {
                    if (input[28] <= 0.07777775824069977) {
                        if (input[51] <= -0.6499999761581421) {
                            memcpy(var58, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                        } else {
                            memcpy(var58, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                        }
                    } else {
                        if (input[49] <= -0.3999999165534973) {
                            if (input[8] <= 0.45000000298023224) {
                                if (input[9] <= 2.699999898672104) {
                                    memcpy(var58, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var58, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[39] <= 0.3660286217927933) {
                                    memcpy(var58, (double[]){0.0, 0.25, 0.75}, 3 * sizeof(double));
                                } else {
                                    memcpy(var58, (double[]){0.0, 0.9, 0.1}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[17] <= 3.75) {
                                if (input[27] <= 0.5252871811389923) {
                                    memcpy(var58, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var58, (double[]){0.0, 0.5121951219512195, 0.4878048780487805}, 3 * sizeof(double));
                                }
                            } else {
                                memcpy(var58, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                            }
                        }
                    }
                } else {
                    memcpy(var58, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                }
            } else {
                memcpy(var58, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var58, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        memcpy(var58, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
    }
    add_vectors(var3, var58, 3, var2);
    double var59[3];
    if (input[4] <= 13.049999713897705) {
        if (input[5] <= 4.25) {
            if (input[5] <= 2.850000023841858) {
                if (input[30] <= 0.03246752917766571) {
                    memcpy(var59, (double[]){1.0, 0.0, 0.0}, 3 * sizeof(double));
                } else {
                    if (input[41] <= 1.1500000357627869) {
                        if (input[57] <= 1.0) {
                            if (input[43] <= -0.4500000476837158) {
                                if (input[52] <= -0.3500000685453415) {
                                    memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                }
                            } else {
                                if (input[57] <= 0.6000000238418579) {
                                    memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var59, (double[]){0.0, 0.8, 0.2}, 3 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[27] <= 0.523809403181076) {
                                memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                            } else {
                                if (input[54] <= -0.9499999284744263) {
                                    memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                                } else {
                                    memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
                    }
                }
            } else {
                memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
        }
    } else {
        if (input[12] <= 80.25) {
            if (input[3] <= 36.89999961853027) {
                memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
            } else {
                memcpy(var59, (double[]){0.0, 0.0, 1.0}, 3 * sizeof(double));
            }
        } else {
            memcpy(var59, (double[]){0.0, 1.0, 0.0}, 3 * sizeof(double));
        }
    }
    add_vectors(var2, var59, 3, var1);
    mul_vector_number(var1, 0.03333333333333333, 3, var0);
    memcpy(output, var0, 3 * sizeof(double));
}


// ── Easy-to-use wrapper ──
// Call this with your 61-feature array
// Returns class index, sets *confidence to vote fraction
int predictMetal(float* features, float* confidence) {
  double input[61];
  for (int i = 0; i < 61; i++) {
    input[i] = (double)features[i];
  }

  double scores[NUM_CLASSES];
  score(input, scores);

  int best = 0;
  double bestScore = scores[0];
  for (int i = 1; i < NUM_CLASSES; i++) {
    if (scores[i] > bestScore) {
      bestScore = scores[i];
      best = i;
    }
  }
  if (confidence != NULL) *confidence = (float)bestScore;
  return best;
}

#endif // METAL_MODEL_H
